# Generated by Django 3.0.7 on 2020-06-25 07:15

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to=articles.models.articles_image_path),
            preserve_default=False,
        ),
    ]
